### ISSUE TITLE
Seg Fault Error for GUI on 2020 Mac M1 Sonoma 14.5

### ISSUE THREAD

**Issue by jadensharp03** [ErwinJr2/ErwinJr2#2]
Followed installation instructions on GitHub and ErwinJr2 Documentation. When opening ErwinJr shortcut and through terminal command, GUI crashes.

**Comment by CareF** [comment]
This app was developed when the apple M seris processors were not published yet, and the default installation downloads some pre-compiled binaries which is not compatible with the ARM CPU. You may need to use a Wfindows/Linux x86-64 computer, or you may need to compile the app locally (following the `Run the software without installation` part of the doc).

**Comment by CareF** [comment]
I updated the deployment and now it should support ARM CPU for apple macos with version >= 2.2.5. 

I don't currently have any devices but please take a look and try if it is OK.
